// src/components/Navbar.vue

<template>
  <header 
    :class="[
      'fixed top-0 left-0 w-full z-40 transition-all duration-300',
      scrolled ? 'glass py-2 shadow-sm' : 'py-4'
    ]"
  >
    <div class="container mx-auto px-4 md:px-6">
      <div class="flex items-center justify-between">
        <router-link to="/" class="flex items-center space-x-2 animate-fade-in">
          <div class="flex items-center gap-2 text-primary">
            <SchoolIcon class="h-8 w-8" />
            <span class="font-bold text-xl hidden sm:inline">A.P.A.C. GOETHE</span>
          </div>
        </router-link>

        <!-- Desktop menu -->
        <nav class="hidden md:flex items-center space-x-6">
          <router-link 
            to="/" 
            class="text-foreground/90 hover:text-foreground font-medium transition-colors"
          >
            Inicio
          </router-link>
          <router-link 
            to="/beneficios" 
            class="text-foreground/90 hover:text-foreground font-medium transition-colors"
          >
            Beneficios
          </router-link>
          <router-link 
            to="/comercios" 
            class="text-foreground/90 hover:text-foreground font-medium transition-colors"
          >
            Comercios
          </router-link>
          <Button as-child variant="ghost" class="gap-1">
            <router-link to="/login">
              <UserCircleIcon class="h-5 w-5 mr-1" />
              Iniciar Sesión
            </router-link>
          </Button>
        </nav>

        <!-- Mobile menu button -->
        <button
          class="md:hidden text-foreground p-2 focus:outline-none"
          @click="toggleMenu"
          aria-label="Menu"
        >
          <XIcon v-if="isMenuOpen" class="h-6 w-6" />
          <MenuIcon v-else class="h-6 w-6" />
        </button>
      </div>
    </div>

    <!-- Mobile menu -->
    <div v-if="isMenuOpen" class="md:hidden glass absolute top-full left-0 w-full py-4 animate-fade-in">
      <div class="container mx-auto px-4">
        <nav class="flex flex-col space-y-4">
          <router-link 
            to="/" 
            class="text-foreground/90 hover:text-foreground font-medium transition-colors py-2"
            @click="closeMenu"
          >
            Inicio
          </router-link>
          <router-link 
            to="/beneficios" 
            class="text-foreground/90 hover:text-foreground font-medium transition-colors py-2"
            @click="closeMenu"
          >
            Beneficios
          </router-link>
          <router-link 
            to="/comercios" 
            class="text-foreground/90 hover:text-foreground font-medium transition-colors py-2"
            @click="closeMenu"
          >
            Comercios
          </router-link>
          <Button as-child variant="default" class="w-full">
            <router-link to="/login" @click="closeMenu">
              <UserCircleIcon class="h-5 w-5 mr-2" />
              Iniciar Sesión
            </router-link>
          </Button>
        </nav>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { useRouter } from 'vue-router';
import { UserCircleIcon, MenuIcon, XIcon, SchoolIcon } from '@heroicons/vue/24/outline';
import { Button } from './ui/button.vue';

const scrolled = ref(false);
const isMenuOpen = ref(false);
const router = useRouter();

const handleScroll = () => {
  const isScrolled = window.scrollY > 20;
  if (isScrolled !== scrolled.value) {
    scrolled.value = isScrolled;
  }
};

const toggleMenu = () => {
  isMenuOpen.value = !isMenuOpen.value;
};

const closeMenu = () => {
  isMenuOpen.value = false;
};

onMounted(() => {
  window.addEventListener('scroll', handleScroll);
});

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll);
});
</script>

// src/components/Navbar.tsx

import { useState, useEffect } from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { UserCircle, Menu, X, School } from 'lucide-react';

const Navbar = () => {
  const [scrolled, setScrolled] = useState(false);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  // This would come from your authentication context in a real app
  const [isLoggedIn, setIsLoggedIn] = useState(true); // Setting to true for demo
  const navigate = useNavigate();
  const location = useLocation();

  useEffect(() => {
    const handleScroll = () => {
      const isScrolled = window.scrollY > 20;
      if (isScrolled !== scrolled) {
        setScrolled(isScrolled);
      }
    };

    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, [scrolled]);

  const toggleMenu = () => setIsMenuOpen(!isMenuOpen);

  return (
    <header 
      className={`fixed top-0 left-0 w-full z-40 transition-all duration-300 ${
        scrolled ? 'glass py-2 shadow-sm' : 'py-4'
      }`}
    >
      <div className="container mx-auto px-4 md:px-6">
        <div className="flex items-center justify-between">
          <Link to="/" className="flex items-center space-x-2 animate-fade-in">
            <div className="flex items-center gap-2 text-primary">
              <School className="h-8 w-8" />
              <span className="font-bold text-xl hidden sm:inline">A.P.A.C. GOETHE</span>
            </div>
          </Link>

          {/* Desktop menu */}
          <nav className="hidden md:flex items-center space-x-6">
            <Link 
              to="/" 
              className="text-foreground/90 hover:text-foreground font-medium transition-colors"
            >
              Inicio
            </Link>
            <Link 
              to="/beneficios" 
              className="text-foreground/90 hover:text-foreground font-medium transition-colors"
            >
              Beneficios
            </Link>
            <Link 
              to="/comercios" 
              className="text-foreground/90 hover:text-foreground font-medium transition-colors"
            >
              Comercios
            </Link>
            {isLoggedIn ? (
              <Button 
                asChild 
                variant={location.pathname === "/perfil" ? "default" : "ghost"} 
                className="gap-1"
              >
                <Link to="/perfil">
                  <UserCircle className="h-5 w-5 mr-1" />
                  Mi Perfil
                </Link>
              </Button>
            ) : (
              <Button 
                asChild 
                variant={location.pathname === "/login" ? "default" : "ghost"} 
                className="gap-1"
              >
                <Link to="/login">
                  <UserCircle className="h-5 w-5 mr-1" />
                  Iniciar Sesión
                </Link>
              </Button>
            )}
          </nav>

          {/* Mobile menu button */}
          <button
            className="md:hidden text-foreground p-2 focus:outline-none"
            onClick={toggleMenu}
            aria-label="Menu"
          >
            {isMenuOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
          </button>
        </div>
      </div>

      {/* Mobile menu */}
      {isMenuOpen && (
        <div className="md:hidden glass absolute top-full left-0 w-full py-4 animate-fade-in">
          <div className="container mx-auto px-4">
            <nav className="flex flex-col space-y-4">
              <Link 
                to="/" 
                className="text-foreground/90 hover:text-foreground font-medium transition-colors py-2"
                onClick={() => setIsMenuOpen(false)}
              >
                Inicio
              </Link>
              <Link 
                to="/beneficios" 
                className="text-foreground/90 hover:text-foreground font-medium transition-colors py-2"
                onClick={() => setIsMenuOpen(false)}
              >
                Beneficios
              </Link>
              <Link 
                to="/comercios" 
                className="text-foreground/90 hover:text-foreground font-medium transition-colors py-2"
                onClick={() => setIsMenuOpen(false)}
              >
                Comercios
              </Link>
              {isLoggedIn ? (
                <Button 
                  asChild 
                  variant="default" 
                  className="w-full"
                >
                  <Link to="/perfil" onClick={() => setIsMenuOpen(false)}>
                    <UserCircle className="h-5 w-5 mr-2" />
                    Mi Perfil
                  </Link>
                </Button>
              ) : (
                <Button 
                  asChild 
                  variant="default" 
                  className="w-full"
                >
                  <Link to="/login" onClick={() => setIsMenuOpen(false)}>
                    <UserCircle className="h-5 w-5 mr-2" />
                    Iniciar Sesión
                  </Link>
                </Button>
              )}
            </nav>
          </div>
        </div>
      )}
    </header>
  );
};

export default Navbar;
